import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Comenzar ahora' }).click();
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.goto('http://localhost:3000/');
  await page.getByText('1. RegístrateCrea tu cuenta').click();
  await page.getByRole('button', { name: 'Comenzar ahora' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre completo' }).fill('J');
  await page.getByRole('textbox', { name: 'Nombre completo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre completo' }).fill('Jona');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('togo36918@gmail.com');
  await page.getByRole('textbox', { name: 'Teléfono' }).click();
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('1123456789');
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).fill('mariposa');
  await page.getByRole('textbox', { name: 'Confirmar contraseña' }).click();
  await page.getByRole('textbox', { name: 'Confirmar contraseña' }).fill('mariposa');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).fill('togo');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).fill('jonatan@gmail.com');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('jonatan@gmail.vom');
  await page.getByRole('textbox', { name: 'Email' }).press('Insert');
  await page.getByRole('textbox', { name: 'Email' }).fill('jonatan@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('mariposa');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Reservar un turno' }).click();
  await page.getByRole('combobox', { name: 'Especialidad' }).click();
  await page.getByRole('option', { name: 'Dermatología' }).click();
  await page.getByRole('combobox', { name: 'Médico' }).click();
  await page.getByRole('option', { name: 'Dr. María García' }).click();
  await page.getByRole('button', { name: 'Fecha' }).click();
  await page.getByRole('gridcell', { name: '14' }).click();
  await page.getByRole('gridcell', { name: '7', exact: true }).click();
  await page.getByRole('combobox', { name: 'Horario' }).click();
  await page.getByRole('option', { name: '14:30' }).click();
  await page.getByRole('button', { name: 'Reservar turno' }).click();
  await page.getByRole('button', { name: 'Fecha' }).click();
  await page.getByRole('gridcell', { name: '8', exact: true }).click();
  await page.getByRole('combobox', { name: 'Horario' }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Reservar turno' }).click();
  await page.locator('body').press('F5');
  await page.goto('http://localhost:3000/dashboard/reservar');
  await page.getByRole('combobox', { name: 'Especialidad' }).click();
  await page.getByRole('option', { name: 'Pediatría' }).click();
  await page.getByRole('combobox', { name: 'Médico' }).click();
  await page.locator('div').filter({ hasText: /^Dr\. Ana Rodríguez$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Fecha' }).click();
  await page.getByRole('gridcell', { name: '8', exact: true }).click();
  await page.getByRole('combobox', { name: 'Horario' }).click();
  await page.getByRole('option', { name: '14:00' }).click();
  await page.getByRole('button', { name: 'Reservar turno' }).click();
  await page.goto('http://localhost:3000/dashboard');
  await page.getByRole('button', { name: 'Reservar nuevo turno' }).click();
  await page.getByRole('combobox', { name: 'Especialidad' }).click();
  await page.getByRole('option', { name: 'Pediatría' }).click();
  await page.getByRole('combobox', { name: 'Médico' }).click();
  await page.getByRole('option', { name: 'Dr. Ana Rodríguez' }).click();
  await page.getByRole('button', { name: 'Fecha' }).click();
  await page.getByRole('gridcell', { name: '23' }).click();
  await page.getByRole('combobox', { name: 'Horario' }).click();
  await page.getByRole('option', { name: '15:00' }).click();
  await page.getByRole('button', { name: 'Reservar turno' }).click();
  await page.getByRole('button', { name: 'Cancelar turno' }).click();
  await page.getByRole('alertdialog', { name: '¿Estás seguro?' }).click();
  await page.getByRole('button', { name: 'Cancelar' }).click();
  await page.getByRole('button', { name: 'Cancelar turno' }).click();
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.getByRole('button', { name: 'Cancelar turno' }).click();
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.getByRole('button', { name: 'Cancelar turno' }).click();
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.goto('http://localhost:3000/dashboard');
  await page.getByRole('button', { name: 'Cancelar turno' }).click();
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.getByRole('link', { name: 'Mi Perfil' }).click();
  await page.goto('http://localhost:3000/dashboard');
  await page.getByRole('link', { name: 'Reservar Turno' }).click();
  await page.getByRole('link', { name: 'MediCitas' }).click();
  await page.getByRole('button', { name: 'Salir' }).click();
  await page.getByRole('link', { name: 'MediCitas' }).click();
  await page.getByRole('link', { name: 'MediCitas' }).click();
  await page.getByRole('link', { name: 'Registrarse' }).click();
  await page.goto('http://localhost:3000/');
});